name: Build APK

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Flutter manually
      - name: Install Flutter
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl unzip xz-utils
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "${GITHUB_WORKSPACE}/flutter/bin" >> $GITHUB_PATH  # Add Flutter to PATH

      # Step 3: Run Flutter Doctor to ensure it's set up
      - name: Run Flutter Doctor
        run: flutter doctor

      # Step 4: Enable Android support and build APK
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release
